# Generated by Django 6.0.4 on 2026-05-05 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_your_trip', models.CharField(choices=[('Diplomatic Forest - Farah Hotel', 'Diplomatic Forest - Farah Hotel'), ('Tangier to Asilah Coast', 'Tangier to Asilah Coast'), ('Tangier to Belyounech', 'Tangier to Belyounech')], max_length=50, verbose_name='Selected Trip')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('datetime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moto.datetime')),
            ],
            options={
                'verbose_name': 'Trip Booking',
                'verbose_name_plural': 'Trip Bookings',
            },
        ),
    ]
