# Generated by Django 6.0.4 on 2026-05-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='select_your_trip',
            field=models.CharField(choices=[('diplomatic_forest', 'diplomatic_forest'), ('asilah_coast', 'asilah_coast'), ('belyounech_mountain', 'belyounech_mountain')], max_length=50, verbose_name='Selected Trip'),
        ),
    ]
